# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Scoreprediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install scikit-learn xgboost requests Flask streamlit pandas

      - name: Check installed packages
        run: pip list

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A7669CD5300475C876506E23D81446A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32F05A65A0124CDCA46B864B69AFE4E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6D9CF41A97DE465A8E0E73B52AAEAD08 }}

      - name: Clean up previous deployments
        run: |
          az webapp deployment source delete --name Scoreprediction --resource-group appsvc_linux_centralus_basic

      - name: Activate virtual environment and install dependencies
        run: |
          ./venv/bin/activate && \
          pip install -r requirements.txt Flask pandas scikit-learn streamlit xgboost requests

      - name: Check installed packages
        run: pip list

      - name: Start API Server
        run: |
          python app.py 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Scoreprediction'
          slot-name: 'Production'
