name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.4.4  # Update to the latest version that explicitly supports Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v2.4.6  # Update to the latest version that explicitly supports Node.js 20
      with:
        python-version: 3.x  # Replace "x" with your Python version (e.g., 3.8)

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust the path if needed

    - name: Run Tests
      run: |
        pytest test.py  # Adjust the test file name if needed
